import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadConfig } from '../../src/config/index.js';
import {
  createProfileFilter,
  enrichModelInfoFromHfConfig,
  type HfConfigJson,
} from '../../src/services/agent-builder-baseline.js';
import type { ModelInfo } from '../../src/types/benchmark.js';

const FIXTURES_DIR = join(__dirname, '..', 'fixtures', 'feature-profiles', 'attack-discovery');

interface ExpectedRow {
  repoId: string;
  fixtureKey: string;
  campaignOutcome: string;
  expectedGateVerdict: 'pass' | 'investigate' | 'reject';
  c2FindingIds: string[];
  note: string;
}

interface ExpectedTable {
  rows: ExpectedRow[];
}

function loadExpectedTable(): ExpectedTable {
  return JSON.parse(readFileSync(join(FIXTURES_DIR, 'expected.json'), 'utf-8')) as ExpectedTable;
}

function loadFixtureConfig(fixtureKey: string): HfConfigJson {
  const raw = readFileSync(join(FIXTURES_DIR, fixtureKey, 'config.json'), 'utf-8');
  return JSON.parse(raw) as HfConfigJson;
}

/**
 * Minimal placeholder ModelInfo carrying only the repo id. Every scored field
 * (architecture, contextWindow, parameterCount, supportsToolCalling) is then
 * derived from the frozen config.json via `enrichModelInfoFromHfConfig` — the
 * same enrichment path production uses — not hand-picked to match expected.json.
 */
function buildPlaceholderModelInfo(repoId: string): ModelInfo {
  return {
    id: repoId,
    name: repoId.split('/')[1] ?? repoId,
    architecture: 'unknown',
    contextWindow: 0,
    license: 'unknown',
    parameterCount: null,
    quantizations: [],
    supportsToolCalling: false,
  };
}

describe('attack-discovery current-vs-expected backtest (step 2)', () => {
  const originalEnv = process.env;

  beforeEach(() => {
    process.env = {
      ...originalEnv,
      SSH_HOST: '10.0.0.1',
      SSH_USERNAME: 'testuser',
      SSH_PASSWORD: 'testpass',
      HUGGINGFACE_TOKEN: 'hf_test_token',
    };
  });

  afterEach(() => {
    process.env = originalEnv;
  });

  it('runs createProfileFilter("attack-discovery") over every frozen fixture and snapshots current-vs-expected', () => {
    const config = loadConfig(undefined, { skipDotenv: true });
    const { success, filter } = createProfileFilter(config, 'attack-discovery');
    expect(success).toBe(true);
    if (!filter) throw new Error('attack-discovery profile produced no filter');

    const table = loadExpectedTable();
    expect(table.rows.length).toBeGreaterThan(0);

    const results = table.rows.map((row) => {
      const hfConfig = loadFixtureConfig(row.fixtureKey);
      const placeholder = buildPlaceholderModelInfo(row.repoId);
      const enriched = enrichModelInfoFromHfConfig(placeholder, hfConfig);
      const filterResult = filter.evaluate(enriched);
      // The current filter is a binary pass/reject gate; it has no "investigate"
      // state yet (that reasoning is added in step 3). Map its binary verdict
      // onto the three-way scale so it can be compared against expected.json.
      const currentVerdict: 'pass' | 'reject' = filterResult.passed ? 'pass' : 'reject';
      return { row, filterResult, currentVerdict };
    });

    // Table is complete: one computed result per expected row, no crashes.
    expect(results).toHaveLength(table.rows.length);

    const lines: string[] = [];
    lines.push('# attack-discovery backtest: current filter vs expected (step 2)');
    lines.push('');
    lines.push(
      'Generated by `tests/unit/feature-profiles-current-backtest.test.ts` against the frozen'
    );
    lines.push(
      'fixtures + `expected.json`. Mismatches are expected at this step and are the input to'
    );
    lines.push(
      'step 3 (the reasoning rules that close the gap) — this test does not fail on them.'
    );
    lines.push('');
    lines.push('| model | expected | current | match | c2 ids | current rejections |');
    lines.push('|---|---|---|---|---|---|');
    for (const { row, filterResult, currentVerdict } of results) {
      const match = row.expectedGateVerdict === currentVerdict ? 'yes' : 'NO';
      const rejections = filterResult.rejections.map((r) => r.criterion).join(', ') || '-';
      lines.push(
        `| ${row.fixtureKey} | ${row.expectedGateVerdict} | ${currentVerdict} | ${match} | ${row.c2FindingIds.join(', ')} | ${rejections} |`
      );
    }
    lines.push('');

    const mismatches = results.filter(({ row, currentVerdict }) => row.expectedGateVerdict !== currentVerdict);
    lines.push(`${mismatches.length} of ${results.length} rows mismatch (expected — step 3 has not run yet).`);
    lines.push('');
    for (const { row, currentVerdict, filterResult } of mismatches) {
      const reasonText = filterResult.rejections.length
        ? `rejected on: ${filterResult.rejections.map((r) => `${r.criterion} — ${r.reason}`).join('; ')}`
        : 'no hard rejections from the current binary filter; the investigate/reject nuance is not expressible yet';
      lines.push(`- ${row.fixtureKey}: expected \`${row.expectedGateVerdict}\`, current filter says \`${currentVerdict}\` (${reasonText})`);
    }
    lines.push('');

    writeFileSync(join(FIXTURES_DIR, 'backtest-current.md'), lines.join('\n'), 'utf-8');

    // This test asserts completeness of the run (every row processed, report
    // written) — not reconciliation with expected.json; see step 3.
    expect(lines.length).toBeGreaterThan(0);
  });
});
